spring:
  application:
    name: department-service
  config:
    import: "optional:configserver:http://localhost:8888"


logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
  level:
    org.springframework.security: DEBUG
    com.oopsmails.spring.cloud.microservices.departmentservice: DEBUG
    com.oopsmails.spring.cloud.microservices.departmentservice.filter.HttpLoggingFilter: DEBUG
