FROM java:8


ADD ./target/springboot2-app-all-backendmock-1.0-SNAPSHOT.jar springboot2-app-all-backendmock-docker.jar


ENTRYPOINT ["java", "-jar", "/springboot2-app-all-backendmock-docker.jar"]


